### PR TITLE
chore: add `files` field in package.json to only include dist files

### PR DESCRIPTION
**Pull request by ydcjeff**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe: package distribution

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

By only including distribution files, this could reduce the package size.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
What's the reason for this change?

**Comment by ydcjeff** [comment]
With this, users don't need to download unnecessary files to use the package. Currently, the distribution includes test directory, coverage, tsconfig files, etc which are not needed from the user view point.

**Comment by ydcjeff** [comment]
Can we merge this PR? @kamilmysliwiec

**Comment by kamilmysliwiec** [comment]
lgtm

**Pull request merged**
