### PR TITLE
make handleRequest promisable

### PR DESCRIPTION
**Pull request by Nishchit14**
In the case where we want to attach some properties to the `request` object which is returning from the database or somewhere else with async. In such situation, the `handleRequest` returns the Promise.

@example
```js
async handleRequest(err, user, info, context): Promise<any> {
        if (err || !user) {
            throw err || new UnauthorizedException();
        }
        const req = context.switchToHttp().getRequest();
        let token = req.headers?.authorization?.split(" ")[1];
        if(token) {
            let tkn = await this.tokenService.getTokenInfo(token);
            if(tkn) {
                req._meta = {
                    token_id: tkn.id,
                    token: tkn.token,
                    user_id: tkn.user_id,
                    client_id: tkn.client_id
                }
            }
        }

        return user;
    }
```

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Return Type added
```

## What is the current behavior?
`handleRequest` in `auth.guard.ts` is not asynchronous

Issue Number: N/A

## What is the new behavior?
`handleRequest` in `auth.guard.ts` will be asynchronous too.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by jmcdo29** [comment]
Any reason you couldn't do this in the `canActivate` which already is `promisable`?

**Comment by Nishchit14** [comment]
Good question, @jmcdo29 
The reason is a sequence of execution. The execution sequence is like
1. canActivate `from jwt.guard.ts)`
2. validate `from jwt.strategy.ts`
3. handleRequest `from jwt.guard.ts`

In my case, I want to attach properties to the `request` object after successful validation (after stage-2). If I fetch info from the database and attach them at `canActive` (stage-1) and then the token fails at validation then the previous database call becomes abandoned.

**Comment by jmcdo29** [comment]
You could still do something like
```ts
can activate(context: Execution context) {
  try {
    await super.canActivate(context)
    // More logic!
  } catch {
    return false;
}
```
And then you still get the same order without having to pass extra values anywhere

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 showed above, you should be able to accomplish what you need with the current API. Thanks for your contribution anyway!

**Comment by drewrawitz** [comment]
Hey guys, just wanted to circle back to this because I'm running into a similar issue. I'm also trying check for `TokenExpiredError` in my JWT auth guard so that I can handle that appropriately.

It would be perfect if I could do it directly in `handleRequest`, because this is currently working:

```
handleRequest(err, user, info, context) {
  if (info.name === "TokenExpiredError") {
    const req = context.getRequest();
    const refreshToken = req?.cookies?.refreshToken;

    if (!refreshToken) {
      throw new UnauthorizedException();
    }

    // Check the Refresh Token in the DB
    // need to use `await` here but am not allowed

    ...
  }
}
```

Except for the fact that I can't do my DB lookup in here because I need it to be asynchronous. 

I'm trying to see if I can use `canActivate`, as suggested above, but I can't seem to wrap my head around it.  What would that look like?  If I try this:

```
async canActivate(context: ExecutionContext): Promise<boolean> {
  try {
    return (await super.canActivate(context)) as boolean;
  } catch (e) {
    console.log(e.name);
  }
}
```

I just get returned back `Error`.  I need to catch that `TokenExpiredError` error and I'm just not sure the best way to do that in `canActivate`.  Any ideas?

**Pull request closed without merging**
