### PR TITLE
fix: move injection of options to a property injection

### PR DESCRIPTION
**Pull request by jmcdo29**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #658 

## What is the new behavior?

By moving to a property injection, we should allow for users to
extend the `AuthGuard()` and pass in some custom properties
via the constructor, but still have full access to `this.options`
and the options can still come from the `PassportModule`

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

I did run prettier on the file which caused a few cosmetic changes. Shouldn't be a big deal, but let me know if I need to revert that.

### CODE REVIEW

**Comment by jmcdo29** [comment]
Also, should we add in an integration test suite to ensure that passport keeps working on upgrades?

**Review by Tony133 — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
That would be awesome @jmcdo29. Would you like to add it to this PR?

**Comment by jmcdo29** [comment]
I used [`pactum`](https://pactumjs.github.io/#/welcome) to facilitate the e2e tests, due to it's flexibility, the fact that it runs against an actual server, and that due to running against a live server it will work with Nest regardless if we use `express` or `fastify` as the underlying engine. I can change this down to `supertest`, but we'll end up managing two versions of tests when we start to support fastify via passport (whenever that will be).

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by ASaiAnudeep** [comment]
@jmcdo29 Thanks for the feedback on `pactum`. With the tiny [pactum-supertest](https://github.com/pactumjs/pactum-supertest) plugin, now `pactum` supports running tests similar to `supertest`. More details here - https://github.com/pactumjs/pactum/discussions/101

**Comment by jmcdo29** [comment]
@ASaiAnudeep Oh cool! Personally, I like having `pactum` and the `app.listen()` calls be separate, but I do see the value for some in just passing the server. I think to pass a Nest server it would still need the `app.getHttpServer()` call like it currently does for supertest. Otherwise that's a nice little plugin there

**Pull request merged**
